Added "paste" and "functions paste" modes.
MatthewCox/igcc pull request #1
Opened 2017-04-10 15:47 UTC by javadba

"Paste" mode allows entering multiline snippets at a single shot.  "Functions Paste" mode allows entering functions that are inserted into the compilation unit  after the #includes sections and before the main.  These are making my life with igcc significantly more effective.

2017-04-10 16:05 UTC, MatthewCox commented
I've been using C++11/14 Lambda functions, but this also seems like a good solution.
I'll take a more detailed look later for merging, but thanks for the contribution!

2017-04-12 11:30 UTC, StarlitGhost requested changes
A couple of typos to fix, but good work overall 👍

2017-04-12 11:30 UTC, MatthewCox commented on README.txt
> +Paste mode is ON: Enter ".f" again to return to return to normal editing.
Shouldn't this be ".p"?

2017-04-12 11:30 UTC, MatthewCox commented on libigcc/dot_commands.py
> +	".N" : ( "Clear all entered commands including user functions ('New')", dot_N ),
I may change .n to take arguments instead, so you can choose which categories you want to wipe.

2017-04-12 11:30 UTC, MatthewCox commented on libigcc/dot_commands.py
> +	print 'Paste mode is ' + ('ON: Enter \".f\" again to return to return to normal editing.' if runner.paste else 'OFF') + '\n'
This should say .p too, right?

2017-04-12 14:03 UTC, javadba commented
No '.f'  toggles function paste mode    .p Toggles paste mode.   You can try it out!
  thx!

2017-04-12 14:06 UTC, javadba commented
There is a subtle difference as well:  toggling "off" the functions paste mode allows further editing whereas toggling off paste mode causes the buffer to be executed.  It makes sense that way. I've been using both of them for doing experiments on both function bodies and  non -function snippets.

2017-04-26 06:01 UTC, javadba commented
Hello?? I responded essentially immediately to your comments but then .. silence ..

2017-04-27 09:16 UTC, MatthewCox commented
> No '.f' toggles function paste mode .p Toggles paste mode.

That's exactly what I'm saying, the 2 messages I pointed out currently say that .f exits the mode entered with .p

2017-04-27 12:55 UTC, javadba commented on README.txt
> +Paste mode is ON: Enter ".f" again to return to return to normal editing.
wow I use that all the time and did not even notice. thx.

2017-04-27 12:56 UTC, javadba commented on libigcc/dot_commands.py
> +	print 'Paste mode is ' + ('ON: Enter \".f\" again to return to return to normal editing.' if runner.paste else 'OFF') + '\n'
Apparently I borked this when adding .f    thx

2017-04-27 12:56 UTC, javadba commented on libigcc/dot_commands.py
> +	".N" : ( "Clear all entered commands including user functions ('New')", dot_N ),
K: I'll add TODO for you.

2017-04-27 13:13 UTC, StarlitGhost approved these changes

2017-04-27 13:14 UTC, merged